# Generated by Django 4.2.1 on 2023-06-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
                ('cuisines', models.TextField(max_length=300)),
                ('price_range', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mezzo_provider', models.CharField(max_length=100)),
                ('order_deeplink', models.URLField(max_length=100)),
                ('has_table_booking', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_delivering_now', models.PositiveBigIntegerField(blank=True, null=True)),
                ('opentable_support', models.PositiveIntegerField(blank=True, null=True)),
                ('has_online_delivery', models.PositiveBigIntegerField(blank=True, null=True)),
                ('include_bogo_offers', models.BooleanField()),
                ('average_cost_for_two', models.PositiveBigIntegerField(blank=True, null=True)),
                ('switch_to_order_menu', models.PositiveBigIntegerField(blank=0, null=0)),
                ('is_book_form_web_view', models.PositiveBigIntegerField(blank=0, null=0)),
                ('book_form_web_view_url', models.URLField(max_length=100)),
                ('is_table_reservation_supported', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('cityid', models.PositiveIntegerField(blank=True, null=True)),
                ('zipcode', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('locality', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('country_id', models.PositiveIntegerField(blank=True, null=True)),
                ('locality_verbose', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rating_text', models.CharField(max_length=100)),
                ('rating_color', models.CharField(max_length=100)),
                ('aggregate_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryid', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('lat_long', models.CharField(max_length=200)),
                ('full_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiafood.details')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiafood.item')),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiafood.location'),
        ),
        migrations.AddField(
            model_name='details',
            name='user_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiafood.rating'),
        ),
    ]
