# Generated by Django 4.2.1 on 2023-06-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indiafood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='food',
            table='Food',
        ),
    ]
