# Generated by Django 4.2.1 on 2023-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiafood', '0002_alter_food_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='items',
            field=models.CharField(choices=[], max_length=200),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
