# Generated by Django 4.2.1 on 2023-06-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiafood', '0003_alter_food_items_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='average_cost_for_two',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='has_online_delivery',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='has_table_booking',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='is_book_form_web_view',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='is_delivering_now',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='is_table_reservation_supported',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='price_range',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='switch_to_order_menu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='votes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
