# Generated by Django 4.2.1 on 2023-06-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiafood', '0004_alter_details_average_cost_for_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='include_bogo_offers',
            field=models.BooleanField(default=False),
        ),
    ]
