# Generated by Django 4.2.1 on 2023-06-23 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indiafood', '0005_alter_details_include_bogo_offers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='details',
            table='Details',
        ),
        migrations.AlterModelTable(
            name='location',
            table='Location',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='Rating',
        ),
    ]
