# Generated by Django 4.2.1 on 2023-06-23 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indiafood', '0007_remove_food_full_details_delete_details_delete_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
                ('cuisines', models.TextField(max_length=300)),
                ('price_range', models.PositiveIntegerField()),
                ('mezzo_provider', models.CharField(max_length=100)),
                ('order_deeplink', models.URLField(max_length=100)),
                ('has_table_booking', models.PositiveIntegerField()),
                ('is_delivering_now', models.PositiveIntegerField()),
                ('opentable_support', models.PositiveIntegerField()),
                ('has_online_delivery', models.PositiveIntegerField()),
                ('include_bogo_offers', models.BooleanField(default=False)),
                ('average_cost_for_two', models.PositiveIntegerField()),
                ('switch_to_order_menu', models.PositiveIntegerField()),
                ('is_book_form_web_view', models.PositiveIntegerField()),
                ('book_form_web_view_url', models.URLField(max_length=100)),
                ('is_table_reservation_supported', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Details',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('cityid', models.PositiveIntegerField()),
                ('zipcode', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('locality', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('country_id', models.PositiveIntegerField()),
                ('locality_verbose', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField()),
                ('rating_text', models.CharField(max_length=100)),
                ('rating_color', models.CharField(max_length=100)),
                ('aggregate_rating', models.FloatField()),
            ],
            options={
                'db_table': 'Rating',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('items', models.CharField(choices=[], max_length=200)),
                ('lat_long', models.CharField(max_length=200)),
                ('full_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiafood.details')),
            ],
            options={
                'db_table': 'Food',
            },
        ),
        migrations.AddField(
            model_name='details',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiafood.location'),
        ),
        migrations.AddField(
            model_name='details',
            name='user_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiafood.rating'),
        ),
    ]
