# Generated by Django 4.2.1 on 2023-06-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indiafood', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='full_details',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
