# Generated by Django 4.2.1 on 2023-06-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiafood', '0011_alter_details_has_online_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
