# Generated by Django 4.2.1 on 2023-06-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiafood', '0012_alter_rating_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='has_online_delivery',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='has_table_booking',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='is_book_form_web_view',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='is_delivering_now',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='is_table_reservation_supported',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='opentable_support',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='switch_to_order_menu',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='primaryid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='cityid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='votes',
            field=models.PositiveIntegerField(),
        ),
    ]
