# Generated by Django 4.2.1 on 2023-06-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiafood', '0013_alter_details_has_online_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
