# Generated by Django 4.2.1 on 2023-06-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiafood', '0014_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
