# Generated by Django 4.2.1 on 2023-06-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indiafood', '0015_alter_food_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='location',
            new_name='detailslocation',
        ),
    ]
